### ISSUE TITLE
LinearPath can divide by zero generating NaN

### ISSUE THREAD

**Issue by Draknek** [useflashpunk/FlashPunk#44]
This happens when two equal points are adjacent in the vertex list.

See: http://flashpunk.net/forums/index.php?topic=2723.0

Probably happens with other motion tweens also?

**Comment by eric-kansas** [comment]
Fixed this issue for a class. If two equal points are adjacent in the vertex list their distance was computed and saved to 0. This was later called in the update() that would return NaN when trying to divide by 0. I fixed it by adding a condition to check if the computed distance was 0 and if it was set it to 1. So when the update() performs the division it returns the same number. This works because there is no distance between two equal points, it is just that point.

**Comment by BlckKnght** [comment]
Hmm, I'm not sure eric's solution really does what we want it to do. Picking 1 as a default distance is arbitrary, and it will cause wrong results if further points are added after the zero-distance segment (consider the two-segment path (0,0), (0,0), (1,0), which should have distance 1, not 2).

I've put together a comprehensive fix, which you can find in commit 1db71a9c.

That patch does two things (which I should have separated into different commits, but didn't bother). First, it ignores attempts to add path segments that have zero length. This prevents the reported zero division as a side effect. Second, it alters the behavior of the class when only a single point has been added (or when a second point was added, but was ignored because it resulted in a zero-length segment). Previously, the tween would throw an exception when you tried to set the motion's duration or speed, now it will simply stay at that single location for the whole period of the tween (it doesn't move).

While I was looking over the forum thread Draknek linked above, I saw that the poster had reported another issue, that the tween was initialized to (0, 0) and didn't return a point on the path until after its first update. That's rather awkward, so I fixed it to immediately set its coordinates to the first point on the path in commit 6635ff59. You can find both commits on my LinearPath-fix branch.

**Comment by Draknek** [comment]
Great, thank you both. :-)
