### ISSUE TITLE
Backdrop doesn't work with big images?

### ISSUE THREAD

**Issue by Draknek** [useflashpunk/FlashPunk#73]
http://flashpunk.net/forums/index.php?topic=3794.0

**Comment by BlckKnght** [comment]
I've investigated this issue. It turned out to be an error in the Canvas class's fillTexture() method. The way it was drawing always caused the texture to be aligned with the underlying buffers the canvas used. This caused the backdrop to repeat after the first 2880 pixels of its texture, then do a weird jump to repeat again when it reached the intended backdrop size.

I've created a fix in commit 5e413ee760.
